import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import Sidebar from "./components/sidebar";
// import TailNav from "./components/tailwind-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full overflow-hidden">
        <Navbar />
        <main className="flex h-[calc(100vh-64px)] flex-row ">
          <Sidebar />
          <div className="flex-1 overflow-y-auto scroll-smooth">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
