import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import Sidebar from "./components/sidebar";
import { getBookMeta } from "@/lib/getProblemsMeta";
// import TailNav from "./components/tailwind-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const book = await getBookMeta()
  if (!book)
    return (
        <html lang="en">
          <body>
            <h1>No Content</h1>
          </body>
        </html>
    )
  return (
    <html lang="en" className="h-screen bg-anti-flash-white dark:bg-sm">
      <body className="h-screen overflow-hidden">
        <Navbar />
        <main className="flex h-[calc(100vh-64px)] flex-row ">
          <Sidebar book={book} />
          <div className="flex-1 overflow-y-auto scroll-smooth bg-anti-flash-white dark:bg-smoky-black">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
